[build]
  # Директория для сборки frontend
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Версия Node.js
  NODE_VERSION = "18"
  # API URL для backend (будет переопределен в Netlify Dashboard)
  VITE_API_URL = "https://export-vkr-production.up.railway.app"

# Перенаправления для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Заголовки для безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Кэширование статических файлов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
